apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  namespace: exp
  labels:
    app: redis-service
spec:
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis-service
          image: docker.io/library/redis
          ports:
            - containerPort: 6379
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: exp
  labels:
    app: redis-service
spec:
  selector:
    app: redis-service
  ports:
    - name: redis
      port: 6379
      targetPort: 6379