kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
   repo: registry.cn-beijing.aliyuncs.com/pivot-yy/ps-devops
   registry: registry.cn-beijing.aliyuncs.com
   dockerfile: code/helloworld/Dockerfile
   username:
    from_secret: docker_username
   password:
    from_secret: docker_password
- name: deliver
  image: sinlead/drone-kubectl
  settings:
   kubernetes_server:
    from_secret: k8s_server
   kubernetes_cert:
    from_secret: k8s_cert
   kubernetes_token:
    from_secret: k8s_token
  commands:
   - kubectl apply -f ./deploy/helloworld.yaml